### ISSUE TITLE
Error when user changes Username

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#104]
On Settings > Edit Profile, if the user tries to change his useranme, there's an error.

**Comment by marcbzz** [comment]
The username is changed but the error comes.

Wouldn't be better to have a fixed username that can't be changed?

**Comment by thiagogabriel** [comment]
@marcbzz I agree with you.
It also makes sense to keep gender field fixed.

**Comment by philss** [comment]
I tried to update username and it works!
This bug was solved?

Maybe the users will feel more confortable with the possibility to change the username(like Twitter).

**Comment by dalthon** [comment]
allowing usrs to change username requires that we renamed all slugs of pages, and doing that, it's impossible to transfer likes from one url to another, so username could not be changed, it's a business rule, and it's fixed not alowing ysers to change their username
