### ISSUE TITLE
Image conflict

### ISSUE THREAD

**Issue by thiagogabriel** [playthecall/playthecall-2013#106]
#### Case:

User A uploads an image called "profile.jpg". 
User B also uploads an image called "profile.jpg". 
Now User A has his profile image changed because they are in the same directory with the same name.
#### There are at least 2 alternatives:
1. Rename each image to a random number like timestamp
2. Upload the image to a subdirectory like playthecall.com/uploads/9/profile.jpg. 9 is the user's ID.

**Comment by badosu** [comment]
Hello @thiagogabriel, did you reproduce this as an error?

Because `CarrierWave` should be handling this.

**Comment by philss** [comment]
Hi @thiagogabriel and @badosu !

I reproduced the problem. It seems that CarrierWave doesn't uses id on diretories. But they have this guide to use random file names: https://github.com/jnicklas/carrierwave/wiki/How-to%3A-Create-random-and-unique-filenames-for-all-versioned-files

Maybe will be the case to use it.

**Comment by badosu** [comment]
Okay! This is a valid issue.

It looks really easy to solve it, just overriding the two methods.

Thank you very much for the info @philss

**Comment by badosu** [comment]
@thiagogabriel This issue is almost an example of a perfect elaborated issue. Very good work dude!!
