### ISSUE TITLE
Create admin page for badges

### ISSUE THREAD

**Issue by sshossain** [playthecall/playthecall-2013#115]

**Comment by eniolopes** [comment]
What is the goal of this page?

It is already posible to upload the badges directly on mission's creation. /cc @badosu @sshossain

**Comment by badosu** [comment]
Is it @eniolopes ? If the badge information can be managed there, accordingly, we can close this issue

**Comment by eniolopes** [comment]
Well, the only informations it really has is a string to find the image and the id of the mission it refers to.

I will close this for now.
