### ISSUE TITLE
Mission Accomplishment Callback

### ISSUE THREAD

**Issue by badosu** [playthecall/playthecall-2013#137]

**Comment by badosu** [comment]
@marcbzz

**Comment by marcbzz** [comment]
E-mail after completing each mission (With link to next mission)

Subject: 

Mission Completed!

E-mail body: 

Greetings Star Hero!

We are happy to announce you just completed your mission, and can now move to the next one. 

Before you rush off too fast to the next mission, just remember that the more you share what you have already accomplished with your friends and community, the more that people will know what you are doing, and they’ll be eager to help you! 

Click on the link below to receive your next mission: 

[LINK}

Keep up the good work!

Your Friends,
The People of the Stars

**Comment by badosu** [comment]
Done!
