### ISSUE TITLE
PORTUGUESE GAME VERSION - ERROR

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#146]
When the player sets the Game Version to portuguese, the link to the mission show up this error.
http://www.playthecall.com/missions/o-chamado

Since the player is logged in, with the error he's unable to log out then the problem persists.

![gameversionptbr](https://f.cloud.github.com/assets/3051176/52566/a62fbe56-5a13-11e2-9248-b305b01e8230.jpg)

**Comment by badosu** [comment]
Done!
