### ISSUE TITLE
End of chapter message after 12th mission

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#159]
Create a page that looks the same than the "welcome" page. But with the text about ending the chapter and waiting for the 2nd chapter.

![endofchapter](https://f.cloud.github.com/assets/3051176/95858/1cef2c6e-6682-11e2-81f8-00aea4be31f2.jpg)

**Comment by marcbzz** [comment]
Here is the text:

The Next Step

At this turning point in time, Star Hero, 
you were asked to awake and you awoke.  
Behold the people of the stars rejoicing.
At this turning point in time, 
you were challenged to show your quality and 
you showed your quality.  
Behold the Earth, our mother, rejoicing.
At this turning point in time, 
you were asked to make a difference and
you were the difference.  
Behold your entire community rejoicing.

A cosmic call was sent out and you answered it, oh how you answered it!
You have officially, and in stellar fashion, completed Chapter I.
We all honor you.
We all celebrate you.
We all invite you to begin Chapter II of the great adventure of your life.

**Comment by marcbzz** [comment]
Still waiting for changes in the end about the date of release of chapter 2.

**Comment by philss** [comment]
Hi there!

I need the pt-BR version of this message. @marcbzz , can you post here or update the `config/locales/pt-BR.yml` file, please? :smile: 

Regards,
Philip

**Comment by marcbzz** [comment]
A Próxima Etapa

Você chegou a um momento decisivo, Herói.
Você foi Chamado para despertar e você despertou.
O Povo das Estrelas está em festa.
Até este momento,
Você foi desafiado a mostrar suas capacidades,
E você as mostrou.
A Terra, nossa criada, está em festa.
Até este momento,
Você foi chamado para mudar,
E você foi a mudança.
Toda sua comunidade está em festa.

O Chamado cósmico foi feito, e você respondeu, e como respondeu!
Você oficialmente, de forma excepcional, 
terminou esse primeiro capítulo.
Nós honramos você.
Nós celebramos seus feitos.
E agora convidamos você para começar o segundo capítulo dessa grande aventura!

Thank you Philip!
<3

**Comment by marcbzz** [comment]
I can upload the locales file if you want me to, but I'll just be able to do that tomorrow or after tomorrow.

Big hugs

**Comment by philss** [comment]
Great @marcbzz !

I have already updated it!
Can someone review it so I can merge?
Thanks! :smile: 

[ ]'s
