### ISSUE TITLE
Mission picture auto-crop

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#161]
The picture uploaded to the mission gets and auto-zoom-crop that many times hides the "important" part of the picture and people cannot even remove it since we don't have the edit mission button.

Example: The candle is not appearing and there is no way to go back.

![autocrop](https://f.cloud.github.com/assets/3051176/101884/2e4e395e-68f9-11e2-855a-88c69eb2befb.jpg)

**Comment by philss** [comment]
This bug was fixed by @fsamuel-bs with 5e3ee0c , so I will close this issue.

Thanks! =)
