### ISSUE TITLE
Fix align of submit buttons

### ISSUE THREAD

**Issue by bezelga** [playthecall/playthecall-2013#170]
![Screen Shot 2013-03-09 at 6 54 19 PM](https://f.cloud.github.com/assets/22406/240312/c7d8c964-8905-11e2-9225-939a7ca7ec9e.png)
![Screen Shot 2013-03-09 at 6 50 47 PM](https://f.cloud.github.com/assets/22406/240313/c7f4ae68-8905-11e2-8676-4fb2039e52d0.png)

**Comment by clauda** [comment]
Vê se é isso

**Comment by philss** [comment]
:+1:
:cool:
