### ISSUE TITLE
Front - "Start to Play"  button and "Sign Up" text

### ISSUE THREAD

**Issue by naimabarbosa-xx** [playthecall/playthecall-2013#23]
'Start to Play' is a button, 
'Sign Up' is just a text link.
Take a look at the picture.
![sign](https://f.cloud.github.com/assets/1951261/15124/48564842-46fc-11e2-94c9-3636ead3d120.jpg)

**Comment by raulsouzalima** [comment]
Fixed!

**Comment by raulsouzalima** [comment]
Adicionei imagem no botão, mal, vou arrumar!

**Comment by badosu** [comment]
Great dude!

**Comment by raulsouzalima** [comment]
Fixed! I also did a refactor on the button style and I created a mixin from it.
