### ISSUE TITLE
Markdown parsing in the mission description

### ISSUE THREAD

**Issue by badosu** [playthecall/playthecall-2013#36]
![Spacement](https://f.cloud.github.com/assets/3051176/15243/413c44ea-4719-11e2-8bf3-98bd448a3b6c.jpg)

**Comment by eniolopes** [comment]
@badosu was it solved? Do we have anyone doing it? /cc @raulsouzalima @krawdyah

**Comment by badosu** [comment]
No, we need to solve it.

The task is more general than that.

We need to apply style to the markdown parsing.

**Comment by raulsouzalima** [comment]
I'm working on it!

**Comment by badosu** [comment]
Thank you, dude!
