### ISSUE TITLE
YouTube link embedded on Mission Page

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#39]
Create video space on Mission instead of image.
Active admin provides each video for each  mission.

![VIDEOmission](https://f.cloud.github.com/assets/3051176/15244/de127050-4719-11e2-816d-30e78f360156.jpg)

**Comment by bezelga** [comment]
![Screen Shot 2012-12-19 at 11 05 03 PM](https://f.cloud.github.com/assets/22406/23464/5ae7d4e2-4a41-11e2-9502-a1f5f5ae5031.png)

@marcbzz like this? or we will just display the link?

**Comment by marcbzz** [comment]
Like that! Awesome!
Thank you so much Fabiano.

With the situation about the quality of the videos, we are not certain if we are going to use videos in this chapter or just the next one (depending on the quality of the video of the new editor), otherwise we will keep using images.

**Comment by bezelga** [comment]
Cool!

In this situation I've added some flexibility for this feature, if you input (via admin interface) the video url then the video will be displayed for the child, if you want to use an image then the video url must be empty and the image attached and if you want to show both on the same mission, just fill the video url and the image and they will be displayed.

If there is any behavior that must be changed, please let me know! =)

**Comment by marcbzz** [comment]
AWESOME. That's the best way possible.
Thank you.

**Comment by badosu** [comment]
Great! Closing it!
