### ISSUE TITLE
Front - Congratulations page 

### ISSUE THREAD

**Issue by naimabarbosa-xx** [playthecall/playthecall-2013#42]
![5-layout-badge](https://f.cloud.github.com/assets/1951261/15287/72663960-472b-11e2-9d76-b8c72cd7508f.jpg)

**Comment by eniolopes** [comment]
Implement this on https://github.com/playthecall/playthecall/pull/41

**Comment by dalthon** [comment]
Now we have no time for this page, i marked as not urgent because is enough right now to congratulate user by email, our users can live with that for 1 or 3 weeks...

**Comment by raulsouzalima** [comment]
I already started to working on it, you can take a look on http://localhost:3000/missions/mission-1/congratulations
We need some integration with back-end here, it's all fake.

**Comment by badosu** [comment]
Done!

@naimabarbosa we dont have the badges with transparency so that the red strip is behind them. But it is done!
