### ISSUE TITLE
User should be able to upload more than one image to mission enrollment

### ISSUE THREAD

**Issue by eniolopes** [playthecall/playthecall-2013#46]

**Comment by eniolopes** [comment]
I need a hand from front enders, any advice here? /cc @krawdyah @raulsouzalima

**Comment by eniolopes** [comment]
![6-layout-missao-maispost](https://f.cloud.github.com/assets/119102/21157/c9ef6524-498a-11e2-9209-0df019167758.png)

**Comment by clauda** [comment]
Isso já está implementado?

**Comment by eniolopes** [comment]
Não, falta a upload multiplo de imagens, tem alguma solução elegante? Já to com o back praticamente feito pra isso, so falta saber qual a solução que vai ser usada no front.

**Comment by clauda** [comment]
pode ser esse https://github.com/ryanb/nested_form

**Comment by clauda** [comment]
eu riz um js pra isso em outro projeto, mas está na outra máquina

**Comment by eniolopes** [comment]
o pro nem é ter mais de um form no mesmo model, é a solução pra fazer upload de mais de uma imagem em um único request, geralmente fazem isso com flash, so queria saber de vossa senhoria se é aceitável usarmos flash ou se tens preferência por alguma lib js que faça isso.

**Comment by eniolopes** [comment]
Que tal?

https://github.com/blueimp/jQuery-File-Upload

**Comment by clauda** [comment]
mano, esse form com as imagens é no new mission_enrollments, mas também deveria estar no status update, não?

**Comment by badosu** [comment]
Is it done?

**Comment by clauda** [comment]
se for só no new tá sim

**Comment by badosu** [comment]
Perfect!
