### ISSUE TITLE
Couldn't find Mission with id=mission-2

### ISSUE THREAD

**Issue by thiagogabriel** [playthecall/playthecall-2013#5]
I don't know why it is returning mission-2 instead of "2" when I go to view.new_mission_mission_enrollment_path(mission)
The URL is: http://localhost:3000/missions/mission-2/mission_enrollments/new but I think it should be http://localhost:3000/missions/2/mission_enrollments/new

**Comment by badosu** [comment]
@eniolopes Pull Request fix this

Thanks @thiagogabriel !!
