### ISSUE TITLE
Front - Corners

### ISSUE THREAD

**Issue by naimabarbosa-xx** [playthecall/playthecall-2013#51]
some corners is not rounded
![Screen Shot 2012-12-16 at 1 55 15 AM](https://f.cloud.github.com/assets/1951261/15316/7fa32d04-4735-11e2-8453-d5874d3f5444.png)

**Comment by marcbzz** [comment]
CLAUDIAAAA MUITO OBRIGADO! Juntos na madrugaaa! ;)

**Comment by clauda** [comment]
:smiley:

**Comment by eniolopes** [comment]
@krawdyah é top
