### ISSUE TITLE
How To Play page

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#54]
How To Play static page appearing between the end of registration and the first missions!

HOME > VIDEO > REGISTRATION > HOW TO PLAY > MISSIONS

**Comment by badosu** [comment]
@marcbzz, please create the how to play page on the admin

**Comment by dalthon** [comment]
I marked as not urgent, we have also other priorities before the end of the world

**Comment by badosu** [comment]
Done: http://www.playthecall.com/pages/how-to-play
