### ISSUE TITLE
Other Social Networks - Links

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#55]
On registration (or other page on settings) we need to put fields to insert other social networks pages and associate this links with the icons below the User's Avatar.

Segue:
![networklinks](https://f.cloud.github.com/assets/3051176/15333/36e16b64-4742-11e2-9a61-b30732805f43.jpg)

**Comment by eniolopes** [comment]
Does this require a integration with the other social networks? /cc @dalthon @badosu

**Comment by badosu** [comment]
We don't have integration with other social networks, we could put a link to PTC's pages on those networks for now

**Comment by raulsouzalima** [comment]
Done!
