### ISSUE TITLE
Can't update user image

### ISSUE THREAD

**Issue by badosu** [playthecall/playthecall-2013#63]
When trying to update user image an error occurs

**Comment by thiagogabriel** [comment]
@badosu Did you try to set the password again? 
I think the problem is that you always have to set the password.

**Comment by badosu** [comment]
@rodrigopinto, i think we could update the issue, or create one, to put the password update page separated

We have it already, /passwords/edit.html.erb. We just need to put the link in the users/edit page.

But even not setting the password I have the problem

**Comment by eniolopes** [comment]
Whats the status here? /cc @badosu

**Comment by badosu** [comment]
I have split the password and profile editing page. 

Since then, the bug could not be reproduced, as far as I know

**Comment by fsamuel-bs** [comment]
Can't reproduce the bug.
