### ISSUE TITLE
User avatar when has no image

### ISSUE THREAD

**Issue by badosu** [playthecall/playthecall-2013#70]
We need to solve this problem:
- We can use a default placeholder
- We validate the presence of the avatar image

**Comment by naimabarbosa-xx** [comment]
![Uploading avatar.jpg . . .]()

@badosu

**Comment by naimabarbosa-xx** [comment]
![avatar](https://f.cloud.github.com/assets/1951261/21465/3c862936-49b0-11e2-8795-388b04ec7c42.jpg)

@badosu

**Comment by badosu** [comment]
@naimabarbosa we need the PNG!
