### ISSUE TITLE
DECLARE "BETA" VERSION

### ISSUE THREAD

**Issue by marcbzz** [playthecall/playthecall-2013#75]
- Have a BETA icon/symbol on every page of the website to make clear that the platform is not completely ready.

**Comment by badosu** [comment]
@naimabarbosa , do you have any idea how can we do this?

**Comment by philss** [comment]
Hi there, 

I'm thinking in something like the "Fork me on Github" banner.
![fork-me - Travis CI example](https://f.cloud.github.com/assets/381213/121334/0c70e0d0-6d8a-11e2-864f-09c5357dac09.png)

What do you think, guys?

Hugs,

**Comment by marcbzz** [comment]
I love it. Do we need a designer to do this?

We can reach Bruno Matinata.

Or is it simples to do? :)

Hugs,

@philss @badosu

**Comment by marcbzz** [comment]
here is the logo with BETA that Bruno did for the homepage!

Let's have it besides the bannerw :)

![ptc_beta_](https://f.cloud.github.com/assets/3051176/121452/03fd3cdc-6d99-11e2-9c09-c885efc8ba61.png)

**Comment by philss** [comment]
\ o /
Great!

For the banner, would be nice if Bruno make it too.
Also, I think we will need the small version of the logo image.

[ ]'s

**Comment by marcbzz** [comment]
![beta_1](https://f.cloud.github.com/assets/3051176/134311/4de1482a-70cd-11e2-8cb7-8992173464f8.png)
![beta_2](https://f.cloud.github.com/assets/3051176/134312/507ff07c-70cd-11e2-89a4-9e4c3116e881.png)

Tá aí! :D 

When can we put this in production?

**Comment by philss** [comment]
Hey @marcbzz , we have this banner in production. But I don't have tried it in IE. Can you test with this browser? I changed the external logo too. =)

**Comment by marcbzz** [comment]
Awesomeee!

I just tested it Phil!
Working on Chrome and IE normally.

You rock. ;)

**Comment by philss** [comment]
Thanks man! So I can close this issue now! :smile:
