### ISSUE TITLE
Development environment is not well described

### ISSUE THREAD

**Issue by badosu** [playthecall/playthecall-2013#8]
We need to update the README to cover the ENV vars setup.

The new collaborators can't setup the development environment with the current information.

**Comment by thiagogabriel** [comment]
I think the only problem I had was with **/config/application/development.yml**
It is missing **$ cp config/application/development.yml.sample config/application/development.yml** and the sample is not with mailer config. Is there something else ?

**Comment by badosu** [comment]
The thing is that we can't put our production setup in `development.yml.sample`, maybe you could help us with this?

Maybe using local mailer?

**Comment by thiagogabriel** [comment]
I don't have enough knowledge about it. I'm updating README.md, what else could I do?

**Comment by thiagogabriel** [comment]
Is it ok ? https://github.com/playthecall/playthecall/pull/25

**Comment by badosu** [comment]
No, as I commented there. The first commit should be reverted before merging

**Comment by badosu** [comment]
#25 solves it
