### ISSUE TITLE
Back & Front - Static pages 

### ISSUE THREAD

**Issue by naimabarbosa-xx** [playthecall/playthecall-2013#84]
if you want psd file, let me know.

![layout-institucional](https://f.cloud.github.com/assets/1951261/21233/40f80fcc-4995-11e2-8c1a-874f4f46e764.jpg)

**Comment by raulsouzalima** [comment]
I'm working on it!

**Comment by raulsouzalima** [comment]
@naimabarbosa send me the psd, sil vous plait.

**Comment by raulsouzalima** [comment]
@badosu please review my work on branch static_pages and fix anything needed please!

**Comment by badosu** [comment]
Ok, I am pull requesting it!
